var myFullName;
console.log(myFullName);
myFullName = "Manisha Salunke";
console.log(myFullName);
var myFullName = "Manisha Dilip Salunke";
console.log(myFullName);
var myLove = '"I love only JS"';
console.log(myLove);
var firstName = "Manisha";
console.log(firstName);
var lastName = "Salunke";
console.log(lastName);
var age = "33";
console.log(age);
var address = "Pirangut,Pune."
console.log(address);
var pincode = "412115";
console.log(pincode);
var gender = "Female";
console.log(gender);
var isMarried = "yes";
console.log(isMarried);